### ISSUE TITLE
.broker:mountPoints() should return more info

### ISSUE THREAD

**Issue by fvacek** [silicon-heaven/shv-doc#6]
It is returning list of strings currently
```
["foo", "bar", "baz"]
```
I suggest to return map `path->client_id`
```
{"foo":1, "bar":2, "baz":3}
```

**Comment by Cynerd** [comment]
Why do you need the clientId? What is the use case?

**Comment by fvacek** [comment]
What is use case for `mountPoints()` for not privileged user?

**Comment by Cynerd** [comment]
It is basically a device index in the broker. Mounted paths are either brokers or devices. In both case you can use .app to identify them and `ls(".broker")` to identify subrokers.

**Comment by fvacek** [comment]
It seems to me to be something resulting from your implementation, not very clear to me. My use-case is that sometimes we need to know ID of client mounted on particular path to provide support to customers. Is mounted paths order in retval imported for you, that it cannot be changed to map?

**Comment by Cynerd** [comment]
https://github.com/silicon-heaven/shv-doc/pull/11

**Comment by fvacek** [comment]
> The order is not essential. I do not care about it. I care just that client id is not necessary info for unpriviledged users. By combining info that is useless to the unpriviledged users with info that is kind of dirty in my eyes.

but mounts is also information which shall not be available to unprivileged user

**Comment by Cynerd** [comment]
> but mounts is also information which shall not be available to unprivileged user

Why it should not be? It is a valid info they can get by looking for `.app` so why hide it? It will allow any client to list all devices without having to go through the whole tree. Of course, broker should filter out inaccessible mount points.

**Comment by fvacek** [comment]
Every client can see different part of SHV tree according to access rights, so `mountPoints()` should be filtered for every client, what is overkill. I think that it doesn't worth to have `mountsPoints()` unprivileged.

**Comment by fvacek** [comment]
`mountPoints()` will be removed from this API version
